=== FrameOS/frameos/frontend/schema/config_json.json
{
  "$ref": "#/definitions/AppConfig",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "AppConfig": {
      "additionalProperties": false,
      "description": "config.json schema",
      "properties": {
        "apt": {
          "description": "List of apt packages to install (mode=rpios)",
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "cache": {
          "$ref": "#/definitions/CacheConfig",
          "description": "Default cache settings"
        },
        "category": {
          "description": "Category for this app",
          "type": "string"
        },
        "description": {
          "description": "Description for this app",
          "type": "string"
        },
        "fields": {
          "description": "Fields for app in diagram editor",
          "items": {
            "anyOf": [
              {
                "$ref": "#/definitions/AppConfigField"
              },
              {
                "$ref": "#/definitions/MarkdownField"
              }
            ]
          },
          "type": "array"
        },
        "name": {
          "description": "Name for this app",
          "type": "string"
        },
        "origin": {
          "description": "Origin app this app was created from, such as repo/apps/code/jsText",
          "type": "string"
        },
        "output": {
          "description": "Returned fields",
          "items": {
            "$ref": "#/definitions/OutputField"
          },
          "type": "array"
        },
        "settings": {
          "description": "List of top level settings exported for this app",
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "version": {
          "description": "Version for this app",
          "type": "string"
        }
      },
      "required": ["name"],
      "type": "object"
    },
    "AppConfigField": {
      "additionalProperties": false,
      "properties": {
        "hint": {
          "description": "Info tooltip contents (markdown)",
          "type": "string"
        },
        "label": {
          "description": "Human readable label",
          "type": "string"
        },
        "name": {
          "description": "Unique config field keyword",
          "type": "string"
        },
        "options": {
          "description": "List of options for the field, only used if type is 'select'",
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "placeholder": {
          "description": "Placeholder text for the field",
          "type": "string"
        },
        "required": {
          "description": "Whether the field is required",
          "type": "boolean"
        },
        "rows": {
          "description": "Number of rows for the field, only used if type is 'text'",
          "type": "number"
        },
        "secret": {
          "description": "Whether the field is a secret and is hidden from display",
          "type": "boolean"
        },
        "seq": {
          "description": "Turn the field into a multidimensional array of fields. seq=[1, \"rows\"] --> for 1 to rows",
          "items": {
            "items": [
              {
                "type": "string"
              },
              {
                "type": ["number", "string"]
              },
              {
                "type": ["number", "string"]
              }
            ],
            "maxItems": 3,
            "minItems": 3,
            "type": "array"
          },
          "type": "array"
        },
        "showIf": {
          "description": "Conditions on which to show the field",
          "items": {
            "anyOf": [
              {
                "$ref": "#/definitions/ConfigFieldCondition"
              },
              {
                "$ref": "#/definitions/ConfigFieldConditionAnd"
              }
            ]
          },
          "type": "array"
        },
        "type": {
          "$ref": "#/definitions/AppConfigFieldType",
          "description": "Type of the field"
        },
        "value": {
          "description": "Default value for the field"
        }
      },
      "required": ["name", "label", "type"],
      "type": "object"
    },
    "AppConfigFieldType": {
      "anyOf": [
        {
          "$ref": "#/definitions/FieldType"
        },
        {
          "const": "select",
          "type": "string"
        },
        {
          "const": "font",
          "type": "string"
        }
      ]
    },
    "CacheConfig": {
      "additionalProperties": false,
      "properties": {
        "duration": {
          "type": "string"
        },
        "durationEnabled": {
          "type": "boolean"
        },
        "enabled": {
          "type": "boolean"
        },
        "expression": {
          "type": "string"
        },
        "expressionEnabled": {
          "type": "boolean"
        },
        "expressionType": {
          "$ref": "#/definitions/FieldType"
        },
        "inputEnabled": {
          "type": "boolean"
        }
      },
      "type": "object"
    },
    "ConfigFieldCondition": {
      "additionalProperties": false,
      "properties": {
        "field": {
          "type": "string"
        },
        "operator": {
          "$ref": "#/definitions/ConfigFieldConditionOperator"
        },
        "value": {}
      },
      "required": ["field"],
      "type": "object"
    },
    "ConfigFieldConditionAnd": {
      "additionalProperties": false,
      "properties": {
        "and": {
          "items": {
            "$ref": "#/definitions/ConfigFieldCondition"
          },
          "type": "array"
        }
      },
      "required": ["and"],
      "type": "object"
    },
    "ConfigFieldConditionOperator": {
      "enum": ["eq", "ne", "gt", "lt", "gte", "lte", "empty", "notEmpty", "in", "notIn"],
      "type": "string"
    },
    "FieldType": {
      "enum": [
        "string",
        "text",
        "float",
        "integer",
        "boolean",
        "color",
        "date",
        "json",
        "node",
        "scene",
        "image",
        "font"
      ],
      "type": "string"
    },
    "MarkdownField": {
      "additionalProperties": false,
      "properties": {
        "markdown": {
          "description": "Block of markdown text to display between fields",
          "type": "string"
        },
        "showIf": {
          "description": "Conditions on which to show the field",
          "items": {
            "$ref": "#/definitions/ConfigFieldCondition"
          },
          "type": "array"
        }
      },
      "required": ["markdown"],
      "type": "object"
    },
    "OutputField": {
      "additionalProperties": false,
      "properties": {
        "example": {
          "description": "Example output (stringified)",
          "type": "string"
        },
        "name": {
          "description": "Name of the output field",
          "type": "string"
        },
        "type": {
          "$ref": "#/definitions/FieldType",
          "description": "Type of the field"
        }
      },
      "required": ["name", "type"],
      "type": "object"
    }
  }
}

=== FrameOS/frameos/frameos/apps/screenshot/config.json
{
  "name": "Screenshot URL",
  "description": "Capture a snapshot of a website. The first time you run this it'll install Fireforx or Chromium and another gigabyte of stuff. This only runs on 64-bit Raspberry Pis!",
  "category": "image",
  "version": "1.0.0",
  "fields": [
    {
      "name": "url",
      "type": "text",
      "value": "https://frameos.net/",
      "required": true,
      "label": "URL to capture",
      "placeholder": ""
    },
    {
      "name": "browser",
      "type": "select",
      "options": ["chromium"],
      "value": "chromium",
      "required": true,
      "label": "Browser"
    },
    {
      "name": "scaling_factor",
      "type": "string",
      "value": "1",
      "required": true,
      "label": "Scaling factor"
    }
  ]
}

=== FrameOS/frameos/frameos/src/apps/render/image/config.json
{
    "name": "Image",
    "description": "Render an image onto a canvas",
    "category": "render",
    "version": "1.0.0",
    "fields": [
        {
            "name": "image",
            "type": "image",
            "required": true,
            "label": "Image"
        },
        {
            "name": "scalingMode",
            "type": "select",
            "options": ["cover", "contain", "stretch", "center"],
            "value": "cover",
            "required": true,
            "label": "Scaling mode"
        },
        {
            "name": "offsetX",
            "type": "integer",
            "value": 0,
            "required": false,
            "label": "Offset X"
        },
        {
            "name": "offsetY",
            "type": "integer",
            "value": 0,
            "required": false,
            "label": "Offset Y"
        }
    ]
}

=== FrameOS/frameos/frameos/src/apps/data/parseJson/config.json
{
  "name": "Parse JSON",
  "description": "Parse a text string and convert to JSON",
  "category": "data",
  "version": "1.0.0",
  "fields": [
    {
      "name": "text",
      "type": "text",
      "required": true,
      "label": "Text"
    }
  ],
  "output": [
    {
      "name": "json",
      "type": "json"
    }
  ]
}

=== FrameOS/frameos/frame/apps/color/config.json
{
  "name": "Color",
  "description": "Set a single color background",
  "category": "image",
  "version": "1.0.0",
  "fields": [
    {
      "name": "effect",
      "type": "select",
      "options": ["none", "pastel-time-rainbow"],
      "value": "none",
      "required": true,
      "label": "Effect"
    },
    {
      "name": "color",
      "type": "string",
      "value": "white",
      "required": true,
      "label": "Color",
      "placeholder": "Enter a color. E.g. white, #ff0000"
    }
  ]
}

=== FrameOS/frameos/frameos/apps/color/config.json
{
  "name": "Color",
  "description": "Set a single color background",
  "category": "image",
  "version": "1.0.0",
  "fields": [
    {
      "name": "color",
      "type": "string",
      "value": "white",
      "required": true,
      "label": "Color",
      "placeholder": "Enter a color. E.g. white, #ff0000"
    }
  ]
}

=== FrameOS/frameos/frameos/apps/break_if_rendering/config.json
{
    "name": "Break if rendering",
    "description": "Abort execution of the current flow if currently rendering.",
    "category": "util",
    "version": "1.0.0",
    "fields": [
        {
            "name": "message",
            "type": "text",
            "value": "",
            "label": "Message to log"
        }
    ]
}

=== FrameOS/frameos/frameos/src/apps/data/icalJson/config.json
{
  "name": "iCal to JSON",
  "description": "Convert an iCal file into a JSON event list",
  "category": "data",
  "version": "1.0.0",
  "fields": [
    {
      "name": "ical",
      "type": "string",
      "required": true,
      "label": "iCal file contents"
    },
    {
      "name": "exportFrom",
      "type": "string",
      "value": "",
      "placeholder": "now",
      "required": false,
      "label": "Export events from (YYYY-MM-DD)"
    },
    {
      "name": "exportUntil",
      "type": "string",
      "value": "",
      "placeholder": "1 year later",
      "required": false,
      "label": "Export events until (YYYY-MM-DD)"
    },
    {
      "name": "exportCount",
      "type": "integer",
      "value": "1000",
      "placeholder": "1000",
      "required": false,
      "label": "Maximum number of events to export"
    },
    {
      "name": "search",
      "type": "string",
      "value": "",
      "placeholder": "",
      "required": false,
      "label": "Filter events by keyword"
    },
    {
      "markdown": "`[{ summary, startTime, endTime, location, description }]`"
    }
  ],
  "output": [
    {
      "name": "events",
      "type": "json"
    }
  ],
  "cache": {
    "enabled": true,
    "inputEnabled": true
  }
}

=== FrameOS/frameos/frameos/src/apps/data/eventsToAgenda/config.json
{
  "name": "Events to Agenda",
  "description": "Convert events to an basic-caret formatted agenda string",
  "category": "data",
  "version": "1.0.0",
  "fields": [
    {
      "name": "events",
      "type": "json",
      "required": true,
      "label": "Events"
    },
    {
      "name": "baseFontSize",
      "type": "float",
      "value": "24",
      "required": true,
      "label": "Base font size"
    },
    {
      "name": "titleFontSize",
      "type": "float",
      "value": "48",
      "required": true,
      "label": "Title font size"
    },
    {
      "name": "titleColor",
      "type": "color",
      "value": "#FFFFFF",
      "required": true,
      "label": "Day title color"
    },
    {
      "name": "textColor",
      "type": "color",
      "value": "#FFFFFF",
      "required": true,
      "label": "Base text color"
    },
    {
      "name": "timeColor",
      "type": "color",
      "value": "#FF0000",
      "required": true,
      "label": "Time color"
    },
    {
      "name": "startWithToday",
      "type": "boolean",
      "value": "true",
      "required": true,
      "label": "Always start with today's date"
    }
  ],
  "output": [
    {
      "name": "result",
      "type": "string"
    }
  ]
}
